# -*- coding: utf-8 -*-
"""Nova_CoPilot_Gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnM5pgMe5FSN2apPnW3OBe1BThbMCQLB

# 🤖 Nova CoPilot for Screens
### Self-learning UI Workflow Automation · Amazon Nova Hackathon 2025

**Powered by:** Nova 2 Lite · Nova Act · Nova Multimodal Embeddings · Nova 2 Sonic

> Run each cell in order. The last cell will deploy a live Gradio UI with a public share link.

---
**Architecture:**
```
Browser Extension  →  Observer Agent  →  Planner Agent (Nova 2 Lite)
                                                  ↓
Ghost Mode (HiTL)  ←  Executor Agent  ←  Nova Act Policy
                                                  ↓
                           Auto Mode + Audit Log + Metrics
```
"""

# ══════════════════════════════════════════════════════════════════════
# CELL 1 — Install Dependencies
# ══════════════════════════════════════════════════════════════════════
print('Installing dependencies...')
!pip install gradio>=4.0 pandas plotly -q
print('✅ All dependencies installed!')

# ══════════════════════════════════════════════════════════════════════
# CELL 2 — Imports & Configuration
# ══════════════════════════════════════════════════════════════════════
import gradio as gr
import pandas as pd
import plotly.graph_objects as go
import json, time, random, math
from datetime import datetime, timedelta
from typing import Generator

print(f'✅ Gradio version: {gr.__version__}')
print(f'✅ Pandas version: {pd.__version__}')

# ══════════════════════════════════════════════════════════════════════
# CELL 3 — Mock Data & Workflow Registry
# ══════════════════════════════════════════════════════════════════════

WORKFLOWS = {
    "Refund Approval": {
        "apps": ["Shopify", "Zendesk"],
        "steps": 7, "confidence": 91, "runs": 30, "errors": 0,
        "saved_min": 15, "status": "auto",
        "description": "Processes pending refund requests in Shopify and closes corresponding Zendesk tickets.",
        "step_list": [
            ("Navigate to Shopify → Orders", 94),
            ("Filter by refund_status:pending", 97),
            ("Open order → verify amount", 89),
            ("Click 'Approve Refund'", 94),
            ("Switch to Zendesk", 96),
            ("Find linked ticket by order ID", 88),
            ("Close ticket with resolution note", 97),
        ],
    },
    "Vendor Onboarding": {
        "apps": ["SAP", "DocuSign", "Email"],
        "steps": 11, "confidence": 84, "runs": 12, "errors": 1,
        "saved_min": 25, "status": "ghost",
        "description": "Onboards new vendors in SAP, sends DocuSign contracts, and triggers confirmation emails.",
        "step_list": [
            ("Open SAP → Vendor Master", 91),
            ("Fill vendor name & GST", 87),
            ("Assign payment terms", 93),
            ("Save vendor record", 96),
            ("Open DocuSign template", 82),
            ("Pre-fill contract fields", 79),
            ("Send for e-signature", 88),
            ("Log in CRM", 84),
            ("Send welcome email", 92),
            ("Create onboarding ticket", 88),
            ("Mark status: Pending Approval", 91),
        ],
    },
    "KYC Document Check": {
        "apps": ["Internal Portal", "DigiLocker"],
        "steps": 5, "confidence": 96, "runs": 47, "errors": 0,
        "saved_min": 8, "status": "auto",
        "description": "Verifies KYC documents against DigiLocker records for customer onboarding.",
        "step_list": [
            ("Login to internal portal", 98),
            ("Fetch pending KYC queue", 95),
            ("Verify Aadhaar via DigiLocker API", 96),
            ("Cross-check PAN details", 94),
            ("Mark KYC status: Verified", 97),
        ],
    },
    "Invoice Reconciliation": {
        "apps": ["Tally", "Email", "Excel"],
        "steps": 9, "confidence": 78, "runs": 5, "errors": 2,
        "saved_min": 35, "status": "draft",
        "description": "Matches received invoices in email against Tally ledger and exports reconciliation report.",
        "step_list": [
            ("Open Gmail → filter invoices", 82),
            ("Download PDF attachments", 86),
            ("Extract invoice number & amount", 74),
            ("Open Tally → Voucher search", 79),
            ("Match by invoice number", 77),
            ("Flag mismatches", 83),
            ("Open Excel template", 91),
            ("Paste reconciled data", 88),
            ("Save & email report", 85),
        ],
    },
}

SESSION_LOG = [
    {"ts": "09:42:01", "icon": "✅", "action": "navigate → shopify/orders", "conf": 97},
    {"ts": "09:42:03", "icon": "✅", "action": "filter → refund_status:pending", "conf": 94},
    {"ts": "09:42:05", "icon": "✅", "action": "click → order #4821", "conf": 91},
    {"ts": "09:42:07", "icon": "✅", "action": "read → amount: ₹1,200", "conf": 99},
    {"ts": "09:42:09", "icon": "⏸️", "action": "awaiting approval → click 'Approve Refund'", "conf": 94},
    {"ts": "09:42:12", "icon": "✅", "action": "navigate → zendesk/tickets", "conf": 96},
    {"ts": "09:42:14", "icon": "✅", "action": "search → order_id:4821", "conf": 88},
    {"ts": "09:42:16", "icon": "⏸️", "action": "awaiting approval → close ticket #ZD-9914", "conf": 87},
]

print('✅ Workflow registry loaded:', list(WORKFLOWS.keys()))

# ══════════════════════════════════════════════════════════════════════
# CELL 4 — Helper Functions
# ══════════════════════════════════════════════════════════════════════

def status_badge(status):
    colors = {"auto": "#10b981", "ghost": "#f59e0b", "draft": "#3b82f6", "error": "#ef4444"}
    labels = {"auto": "🤖 AUTO", "ghost": "👁 GHOST", "draft": "📝 DRAFT", "error": "❌ ERROR"}
    c = colors.get(status, "#64748b")
    l = labels.get(status, status.upper())
    return f'<span style="background:{c};color:#000;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;">{l}</span>'

def confidence_bar(conf):
    color = "#10b981" if conf >= 90 else "#f59e0b" if conf >= 75 else "#ef4444"
    return (
        f'<div style="display:flex;align-items:center;gap:8px;">'
        f'<div style="flex:1;height:6px;background:#1e2d4d;border-radius:3px;overflow:hidden;">'
        f'<div style="width:{conf}%;height:100%;background:{color};"></div></div>'
        f'<span style="font-family:monospace;font-size:12px;color:{color};min-width:32px;">{conf}%</span>'
        f'</div>'
    )

def make_html_card(title, value, subtitle, color):
    return (
        f'<div style="background:#0f1628;border:1px solid #1e2d4d;border-radius:10px;padding:20px;border-top:3px solid {color};">'
        f'<div style="font-family:monospace;font-size:11px;color:#64748b;margin-bottom:4px;">{subtitle}</div>'
        f'<div style="font-size:2rem;font-weight:800;color:{color};letter-spacing:-0.03em;">{value}</div>'
        f'<div style="font-size:13px;color:#94a3b8;margin-top:4px;">{title}</div>'
        f'</div>'
    )

print('✅ Helper functions ready')

# ══════════════════════════════════════════════════════════════════════
# CELL 5 — Dashboard Functions
# ══════════════════════════════════════════════════════════════════════

def get_dashboard_html():
    total_runs = sum(w["runs"] for w in WORKFLOWS.values())
    total_saved = sum(w["runs"] * w["saved_min"] for w in WORKFLOWS.values())
    total_errors = sum(w["errors"] for w in WORKFLOWS.values())
    accuracy = round((1 - total_errors / max(total_runs, 1)) * 100, 1)

    cards = (
        make_html_card("Total Automation Runs", total_runs, "all workflows", "#06b6d4") +
        make_html_card("Minutes Saved", f"{total_saved:,}", "cumulative", "#10b981") +
        make_html_card("Accuracy Rate", f"{accuracy}%", "post human review", "#3b82f6") +
        make_html_card("Active Workflows", len(WORKFLOWS), "configured", "#f59e0b")
    )
    cards_html = f'<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:24px;">{cards}</div>'

    rows = ""
    for name, w in WORKFLOWS.items():
        badge = status_badge(w["status"])
        conf_bar = confidence_bar(w["confidence"])
        apps = " · ".join(w["apps"])
        rows += (
            f'<tr style="border-bottom:1px solid #1e2d4d;">'
            f'<td style="padding:12px 8px;font-weight:600;">{name}</td>'
            f'<td style="padding:12px 8px;font-family:monospace;font-size:12px;color:#64748b;">{apps}</td>'
            f'<td style="padding:12px 8px;">{badge}</td>'
            f'<td style="padding:12px 8px;min-width:150px;">{conf_bar}</td>'
            f'<td style="padding:12px 8px;font-family:monospace;color:#06b6d4;">{w["runs"]}</td>'
            f'<td style="padding:12px 8px;font-family:monospace;color:#10b981;">{w["runs"]*w["saved_min"]} min</td>'
            f'</tr>'
        )

    table_html = (
        f'<div style="background:#0f1628;border:1px solid #1e2d4d;border-radius:10px;overflow:hidden;">'
        f'<div style="padding:14px 16px;border-bottom:1px solid #1e2d4d;font-family:monospace;font-size:12px;color:#06b6d4;">// WORKFLOW REGISTRY</div>'
        f'<table style="width:100%;border-collapse:collapse;">'
        f'<thead><tr style="background:#060810;">'
        f'<th style="padding:10px 8px;text-align:left;font-size:11px;color:#64748b;font-family:monospace;">WORKFLOW</th>'
        f'<th style="padding:10px 8px;text-align:left;font-size:11px;color:#64748b;font-family:monospace;">APPS</th>'
        f'<th style="padding:10px 8px;text-align:left;font-size:11px;color:#64748b;font-family:monospace;">STATUS</th>'
        f'<th style="padding:10px 8px;text-align:left;font-size:11px;color:#64748b;font-family:monospace;">CONFIDENCE</th>'
        f'<th style="padding:10px 8px;text-align:left;font-size:11px;color:#64748b;font-family:monospace;">RUNS</th>'
        f'<th style="padding:10px 8px;text-align:left;font-size:11px;color:#64748b;font-family:monospace;">SAVED</th>'
        f'</tr></thead><tbody>{rows}</tbody></table></div>'
    )
    return cards_html + table_html

def get_runs_chart():
    dates = [datetime.now() - timedelta(days=6-i) for i in range(7)]
    fig = go.Figure()
    colors = {"Refund Approval": "#06b6d4", "Vendor Onboarding": "#f59e0b",
              "KYC Document Check": "#10b981", "Invoice Reconciliation": "#3b82f6"}
    for name, w in WORKFLOWS.items():
        base = w["runs"] // 7
        vals = [max(0, base + random.randint(-2, 4)) for _ in range(7)]
        fig.add_trace(go.Scatter(
            x=[d.strftime("%b %d") for d in dates], y=vals,
            name=name, line=dict(color=colors[name], width=2),
            mode="lines+markers", marker=dict(size=5),
        ))
    fig.update_layout(
        paper_bgcolor="#060810", plot_bgcolor="#060810",
        font=dict(family="monospace", color="#94a3b8", size=11),
        legend=dict(bgcolor="#0f1628", bordercolor="#1e2d4d", borderwidth=1),
        xaxis=dict(gridcolor="#1e2d4d"), yaxis=dict(gridcolor="#1e2d4d"),
        margin=dict(l=40, r=20, t=40, b=40), height=260,
        title=dict(text="Automation Runs — Last 7 Days", font=dict(size=13, color="#f8fafc")),
    )
    return fig

def get_confidence_chart():
    names = list(WORKFLOWS.keys())
    confs = [w["confidence"] for w in WORKFLOWS.values()]
    colors = ["#10b981" if c >= 90 else "#f59e0b" if c >= 75 else "#ef4444" for c in confs]
    fig = go.Figure(go.Bar(
        x=confs, y=[n[:18] for n in names], orientation="h",
        marker=dict(color=colors), text=[f"{c}%" for c in confs],
        textposition="outside", textfont=dict(size=12, color="#f8fafc"),
    ))
    fig.update_layout(
        paper_bgcolor="#060810", plot_bgcolor="#060810",
        font=dict(family="monospace", color="#94a3b8", size=11),
        xaxis=dict(range=[0, 110], gridcolor="#1e2d4d"),
        yaxis=dict(gridcolor="rgba(0,0,0,0)"),
        margin=dict(l=10, r=60, t=40, b=30), height=200,
        title=dict(text="Confidence by Workflow", font=dict(size=13, color="#f8fafc")),
        bargap=0.3,
    )
    return fig

print('✅ Dashboard functions ready')

# ══════════════════════════════════════════════════════════════════════
# CELL 6 — Workflow Builder & Ghost Mode Functions
# ══════════════════════════════════════════════════════════════════════

def simulate_recording():
    steps = [
        ("🔴 Starting browser extension recorder...", 0.5),
        ("📍 URL captured: shopify.com/admin/orders", 0.4),
        ("🖱️  Click detected: nav-link[data-id='orders']", 0.3),
        ("📸 Screenshot saved: orders_list_001.png", 0.4),
        ("🖱️  Click detected: filter-dropdown[name='status']", 0.3),
        ("⌨️  Input: 'pending' → filter applied", 0.4),
        ("📍 URL: /orders?status=pending&sort=date_desc", 0.3),
        ("🖱️  Click detected: order-row[id='4821']", 0.4),
        ("📸 Screenshot saved: order_detail_4821.png", 0.3),
        ("🔍 DOM element: button.refund-approve detected", 0.4),
        ("🛡️  PII MASKED: customer email → [REDACTED]", 0.3),
        ("🛡️  PII MASKED: phone number → [REDACTED]", 0.3),
        ("🖱️  Click detected: button.refund-approve", 0.5),
        ("✅  Action confirmed: refund_status → approved", 0.3),
        ("🔄  App switch detected → zendesk.com", 0.4),
        ("🔍  Search: ticket linked to order_id=4821", 0.3),
        ("🖱️  Click detected: btn-close-ticket", 0.4),
        ("✅  Ticket #ZD-9914 closed", 0.3),
        ("", 0.3),
        ("━"*40, 0.1),
        ("✅  SESSION COMPLETE · 18 actions captured", 0.2),
        ("🧠  Sending to Nova 2 Lite for analysis...", 0.5),
        ("", 0.2),
        ("╔" + "═"*38 + "╗", 0.1),
        ("║  NOVA 2 LITE · WORKFLOW ANALYSIS       ║", 0.1),
        ("╚" + "═"*38 + "╝", 0.2),
        ("📋  Workflow detected: 'Refund Approval'", 0.4),
        ("🔗  Apps: Shopify → Zendesk (cross-app)", 0.3),
        ("📝  Steps identified: 7 distinct actions", 0.3),
        ("📊  Confidence score: 91%", 0.4),
        ("🤖  Nova Act policy generated successfully", 0.3),
        ("", 0.2),
        ("🚀  Workflow ready for Ghost Mode review!", 0.1),
    ]
    log = ""
    for text, delay in steps:
        log += text + "\n"
        yield log
        time.sleep(delay)

def get_workflow_steps_html(workflow_name):
    if workflow_name not in WORKFLOWS:
        return "<p>Select a workflow.</p>"
    w = WORKFLOWS[workflow_name]
    rows = ""
    for i, (step, conf) in enumerate(w["step_list"], 1):
        color = "#10b981" if conf >= 90 else "#f59e0b" if conf >= 75 else "#ef4444"
        icon = "✅" if conf >= 90 else "⚠️" if conf >= 75 else "❌"
        rows += (
            f'<div style="display:flex;align-items:center;gap:12px;padding:10px;'
            f'border-bottom:1px solid #1e2d4d;background:{"#0a0e1a" if i%2==0 else "transparent"};">'
            f'<span style="font-family:monospace;font-size:11px;color:#64748b;min-width:20px;">{i:02d}</span>'
            f'<span style="flex:1;font-size:13px;">{step}</span>'
            f'<span style="font-size:16px;">{icon}</span>'
            f'<div style="width:80px;height:5px;background:#1e2d4d;border-radius:2px;overflow:hidden;">'
            f'<div style="width:{conf}%;height:100%;background:{color};"></div></div>'
            f'<span style="font-family:monospace;font-size:11px;color:{color};min-width:32px;">{conf}%</span>'
            f'</div>'
        )
    badge = status_badge(w["status"])
    return (
        f'<div style="background:#0f1628;border:1px solid #1e2d4d;border-radius:10px;overflow:hidden;">'
        f'<div style="padding:14px 16px;border-bottom:1px solid #1e2d4d;display:flex;justify-content:space-between;align-items:center;">'
        f'<span style="font-family:monospace;font-size:12px;color:#06b6d4;">// {workflow_name.upper()}</span>'
        f'{badge}</div>'
        f'<div style="padding:8px 16px;border-bottom:1px solid #1e2d4d;font-size:12px;color:#64748b;">{w["description"]}</div>'
        f'{rows}</div>'
    )

def get_ghost_panel(workflow_name):
    if workflow_name not in WORKFLOWS:
        return "<p>Select a workflow.</p>"
    w = WORKFLOWS[workflow_name]
    pending = [(s, c) for s, c in w["step_list"] if c < 95][:3]
    rows = ""
    for step, conf in pending:
        color = "#f59e0b" if conf >= 75 else "#ef4444"
        rows += (
            f'<div style="border:1px dashed {color}40;border-radius:8px;padding:12px 14px;'
            f'background:{color}10;margin-bottom:8px;display:flex;justify-content:space-between;align-items:center;">'
            f'<span style="font-size:13px;">{step}</span>'
            f'<span style="font-family:monospace;font-size:12px;color:{color};background:{color}20;'
            f'padding:2px 8px;border-radius:4px;">{conf}%</span>'
            f'</div>'
        )
    return (
        f'<div style="background:#0f1628;border:1px solid #f59e0b40;border-radius:10px;overflow:hidden;">'
        f'<div style="padding:12px 16px;background:#f59e0b15;border-bottom:1px solid #f59e0b30;'
        f'font-family:monospace;font-size:12px;color:#f59e0b;">👁 GHOST MODE ACTIVE — AWAITING YOUR APPROVAL</div>'
        f'<div style="padding:16px;">'
        f'<p style="font-size:13px;color:#94a3b8;margin-bottom:12px;">Actions needing review before agent proceeds:</p>'
        f'{rows}'
        f'<div style="font-family:monospace;font-size:11px;color:#64748b;margin-top:12px;">'
        f'Workflow: {workflow_name} · Steps: {w["steps"]} · Confidence: {w["confidence"]}%</div>'
        f'</div></div>'
    )

def approve_ghost(workflow_name):
    WORKFLOWS[workflow_name]["runs"] += 1
    log = f"✅  [{datetime.now().strftime('%H:%M:%S')}]  APPROVED → {workflow_name}\n"
    log += f"    Agent proceeding with {WORKFLOWS[workflow_name]['steps']} actions...\n"
    log += f"    Run #{WORKFLOWS[workflow_name]['runs']} logged to audit trail.\n"
    return log, f"✅ Approved! Run #{WORKFLOWS[workflow_name]['runs']} logged."

def reject_ghost(workflow_name):
    log = f"⏸️  [{datetime.now().strftime('%H:%M:%S')}]  SKIPPED → {workflow_name}\n"
    log += "    Agent paused. Correction noted for model improvement.\n"
    return log, "⏸️ Step skipped. Agent paused for correction."

def promote_to_auto(workflow_name):
    if workflow_name in WORKFLOWS:
        WORKFLOWS[workflow_name]["status"] = "auto"
        return f"🤖 '{workflow_name}' promoted to AUTO MODE!"
    return "Workflow not found."

print('✅ Workflow & Ghost Mode functions ready')

# ══════════════════════════════════════════════════════════════════════
# CELL 7 — ROI Calculator & Audit Log Functions
# ══════════════════════════════════════════════════════════════════════

def calc_roi(team_size, hrs_per_day, hourly_rate, automation_rate):
    auto = automation_rate / 100
    saved_hrs_day = hrs_per_day * auto
    saved_hrs_month = round(team_size * saved_hrs_day * 22, 1)
    saved_cost_month = round(saved_hrs_month * hourly_rate)
    saved_cost_year = saved_cost_month * 12
    fte_equivalent = round(saved_hrs_month / 176, 1)
    setup_cost = 50000
    weeks_payback = round(setup_cost / (saved_cost_month / 4.3)) if saved_cost_month > 0 else 999
    community_hrs_week = round(team_size * saved_hrs_day * 5)

    return f"""
╔══════════════════════════════════════════════════════╗
║           ROI ANALYSIS · NOVA COPILOT                ║
╚══════════════════════════════════════════════════════╝

📊  INPUT PARAMETERS
    ├── Team size          : {team_size} people
    ├── Manual hrs/day     : {hrs_per_day} hrs per person
    ├── Hourly rate        : ₹{hourly_rate:,}
    └── Automation rate    : {automation_rate}%

⏱️  TIME SAVINGS
    ├── Saved per person/day : {saved_hrs_day:.1f} hrs
    ├── Saved team/month     : {saved_hrs_month:,} hrs
    └── FTE equivalent       : {fte_equivalent} full-time employees

💰  COST SAVINGS
    ├── Monthly savings    : ₹{saved_cost_month:,}
    ├── Annual savings     : ₹{saved_cost_year:,}
    └── Payback period     : {"< 2 weeks" if weeks_payback <= 2 else f"~{weeks_payback} weeks"}

🌍  COMMUNITY IMPACT
    └── Hours returned to real work/week : {community_hrs_week} hrs

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅  RECOMMENDATION: {"STRONG GO — High ROI" if saved_cost_month > 100000 else "GO — Positive ROI" if saved_cost_month > 30000 else "PILOT FIRST — Moderate ROI"}
"""

def get_roi_chart(team_size, hrs_per_day, hourly_rate, automation_rate):
    months = list(range(1, 13))
    saved_per_month = team_size * hrs_per_day * (automation_rate/100) * 22 * hourly_rate
    setup = 50000
    cumulative = [round(saved_per_month * m - setup) for m in months]
    fig = go.Figure()
    fig.add_hline(y=0, line_dash="dash", line_color="#64748b", line_width=1)
    fig.add_trace(go.Scatter(
        x=[f"M{m}" for m in months], y=cumulative,
        fill="tozeroy", line=dict(color="#06b6d4", width=2),
        fillcolor="rgba(6,182,212,0.1)", mode="lines+markers",
        marker=dict(size=6, color=["#ef4444" if v < 0 else "#10b981" for v in cumulative]),
        hovertemplate="Month %{x}<br>₹%{y:,.0f}<extra></extra>",
    ))
    fig.update_layout(
        paper_bgcolor="#060810", plot_bgcolor="#060810",
        font=dict(family="monospace", color="#94a3b8", size=11),
        xaxis=dict(gridcolor="#1e2d4d"), yaxis=dict(gridcolor="#1e2d4d", tickprefix="₹", tickformat=","),
        margin=dict(l=60, r=20, t=40, b=40), height=300,
        title=dict(text="Cumulative ROI Over 12 Months", font=dict(size=13, color="#f8fafc")),
    )
    return fig

def get_audit_log_df():
    rows = []
    base = datetime.now() - timedelta(hours=2)
    for i, entry in enumerate(SESSION_LOG):
        rows.append({
            "Timestamp": (base + timedelta(seconds=i*90)).strftime("%Y-%m-%d %H:%M:%S"),
            "Status": entry["icon"],
            "Action": entry["action"],
            "Confidence": f"{entry['conf']}%",
            "Workflow": "Refund Approval",
            "Agent": "Executor Agent",
        })
    for wf_name, w in list(WORKFLOWS.items())[1:]:
        for j in range(min(w["runs"], 5)):
            rows.append({
                "Timestamp": (base - timedelta(minutes=j*15)).strftime("%Y-%m-%d %H:%M:%S"),
                "Status": "✅",
                "Action": f"auto_execute → {wf_name.lower().replace(' ','_')} (run #{w['runs']-j})",
                "Confidence": f"{w['confidence']}%",
                "Workflow": wf_name,
                "Agent": "Executor Agent",
            })
    return pd.DataFrame(rows)

def export_audit(fmt):
    df = get_audit_log_df()
    path = f"/tmp/nova_copilot_audit.{'csv' if fmt == 'CSV' else 'json'}"
    if fmt == "CSV":
        df.to_csv(path, index=False)
    else:
        df.to_json(path, orient="records", indent=2)
    return path, f"✅ Exported {len(df)} records."

print('✅ ROI & Audit functions ready')

# ══════════════════════════════════════════════════════════════════════
# CELL 8 — CSS & Header
# ══════════════════════════════════════════════════════════════════════

CSS = """
body, .gradio-container { background: #060810 !important; }
.gradio-container { max-width: 1200px !important; }
.tab-nav button { background: #0f1628 !important; border: 1px solid #1e2d4d !important;
  color: #94a3b8 !important; border-radius: 8px !important; font-family: monospace !important; font-size: 12px !important; }
.tab-nav button.selected { background: #1e2d4d !important; color: #06b6d4 !important; border-color: #06b6d4 !important; }
input[type=text], textarea, .block { background: #0f1628 !important; border: 1px solid #1e2d4d !important;
  color: #f8fafc !important; border-radius: 8px !important; }
button.primary { background: #2563eb !important; border: none !important; color: white !important;
  border-radius: 8px !important; font-weight: 600 !important; }
button.secondary { background: #0f1628 !important; border: 1px solid #1e2d4d !important;
  color: #94a3b8 !important; border-radius: 8px !important; }
input[type=range] { accent-color: #06b6d4 !important; }
label span { color: #94a3b8 !important; font-family: monospace !important; font-size: 12px !important; }
"""

HEADER_HTML = """
<link href="https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=DM+Mono&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet">
<div style="background:linear-gradient(135deg,#0b0f1c 0%,#0f1628 100%);border:1px solid #1e2d4d;
     border-radius:12px;padding:28px 32px;margin-bottom:16px;position:relative;overflow:hidden;">
  <div style="position:relative;z-index:1;">
    <div style="font-family:'DM Mono',monospace;font-size:11px;color:#06b6d4;letter-spacing:0.1em;margin-bottom:8px;">
      ● NOVA COPILOT FOR SCREENS · AMAZON NOVA HACKATHON 2025</div>
    <h1 style="font-family:'Syne',sans-serif;font-size:2.2rem;font-weight:800;letter-spacing:-0.04em;
         color:#f8fafc;margin:0 0 8px 0;line-height:1.1;">
      Self-learning <span style="color:#06b6d4;">UI Workflow</span> Automation</h1>
    <p style="color:#64748b;font-size:14px;font-weight:300;margin:0 0 16px 0;max-width:600px;">
      Watch real work happen → learn from it → safely automate 80% of the clicks.</p>
    <div style="display:flex;gap:8px;flex-wrap:wrap;">
      <span style="background:#2563eb20;border:1px solid #2563eb60;color:#3b82f6;padding:3px 10px;border-radius:100px;font-family:monospace;font-size:11px;">Nova 2 Lite</span>
      <span style="background:#06b6d420;border:1px solid #06b6d460;color:#06b6d4;padding:3px 10px;border-radius:100px;font-family:monospace;font-size:11px;">Nova Act</span>
      <span style="background:#f59e0b20;border:1px solid #f59e0b60;color:#f59e0b;padding:3px 10px;border-radius:100px;font-family:monospace;font-size:11px;">Nova Embeddings</span>
      <span style="background:#10b98120;border:1px solid #10b98160;color:#10b981;padding:3px 10px;border-radius:100px;font-family:monospace;font-size:11px;">Nova 2 Sonic</span>
    </div>
  </div>
</div>
"""

print('✅ CSS & HTML ready')

# ══════════════════════════════════════════════════════════════════════
# CELL 9 — BUILD & LAUNCH GRADIO APP  🚀
# ══════════════════════════════════════════════════════════════════════

def build_and_launch():
    with gr.Blocks(css=CSS, theme=gr.themes.Base(), title="Nova CoPilot for Screens") as demo:

        gr.HTML(HEADER_HTML)

        with gr.Tabs():

            # ── TAB 1: DASHBOARD
            with gr.TabItem("📊  Dashboard"):
                gr.HTML('<div style="font-family:monospace;font-size:11px;color:#06b6d4;padding:8px 0;">// LIVE DASHBOARD</div>')
                dashboard_html = gr.HTML(get_dashboard_html())
                with gr.Row():
                    runs_chart = gr.Plot(get_runs_chart(), label="")
                    conf_chart = gr.Plot(get_confidence_chart(), label="")
                gr.Button("↻  Refresh", variant="secondary", size="sm").click(
                    fn=lambda: (get_dashboard_html(), get_runs_chart(), get_confidence_chart()),
                    outputs=[dashboard_html, runs_chart, conf_chart]
                )

            # ── TAB 2: WORKFLOW BUILDER
            with gr.TabItem("🔧  Workflow Builder"):
                gr.HTML('<div style="font-family:monospace;font-size:11px;color:#06b6d4;padding:8px 0;">// RECORD → ANALYSE → GENERATE</div>')
                with gr.Row():
                    with gr.Column():
                        rec_btn = gr.Button("⏺  Start Recording Simulation", variant="primary")
                        rec_out = gr.Textbox(label="Session Log", lines=20, interactive=False)
                        rec_btn.click(fn=simulate_recording, outputs=rec_out)
                    with gr.Column():
                        wf_sel = gr.Dropdown(choices=list(WORKFLOWS.keys()), value="Refund Approval", label="Select Workflow")
                        steps_html = gr.HTML(get_workflow_steps_html("Refund Approval"))
                        wf_sel.change(fn=get_workflow_steps_html, inputs=wf_sel, outputs=steps_html)

            # ── TAB 3: GHOST MODE
            with gr.TabItem("👁  Ghost Mode"):
                gr.HTML('<div style="font-family:monospace;font-size:11px;color:#f59e0b;padding:8px 0;">// GHOST MODE · Human-in-the-Loop Control</div>')
                with gr.Row():
                    with gr.Column():
                        ghost_wf = gr.Dropdown(choices=list(WORKFLOWS.keys()), value="Vendor Onboarding", label="Active Workflow")
                        ghost_panel = gr.HTML(get_ghost_panel("Vendor Onboarding"))
                        ghost_wf.change(fn=get_ghost_panel, inputs=ghost_wf, outputs=ghost_panel)
                        with gr.Row():
                            app_btn = gr.Button("✅  Approve & Execute", variant="primary")
                            rej_btn = gr.Button("⏸  Skip / Correct", variant="secondary")
                        prom_btn = gr.Button("🤖  Promote to AUTO MODE", variant="primary")
                        prom_status = gr.Textbox(label="Status", interactive=False)
                    with gr.Column():
                        dec_log = gr.Textbox(label="Decision Log", lines=12, interactive=False, value="// Waiting...\n")
                        dec_status = gr.Textbox(label="Status", interactive=False)
                app_btn.click(fn=approve_ghost, inputs=ghost_wf, outputs=[dec_log, dec_status])
                rej_btn.click(fn=reject_ghost, inputs=ghost_wf, outputs=[dec_log, dec_status])
                prom_btn.click(fn=promote_to_auto, inputs=ghost_wf, outputs=prom_status)

            # ── TAB 4: ROI CALCULATOR
            with gr.TabItem("💰  ROI Calculator"):
                gr.HTML('<div style="font-family:monospace;font-size:11px;color:#10b981;padding:8px 0;">// ROI CALCULATOR</div>')
                with gr.Row():
                    with gr.Column():
                        t_size = gr.Slider(1, 200, value=10, step=1, label="Team size (people)")
                        h_day  = gr.Slider(0.5, 6.0, value=2.0, step=0.25, label="Manual hrs/person/day")
                        h_rate = gr.Slider(200, 3000, value=500, step=100, label="Avg hourly cost (₹)")
                        a_rate = gr.Slider(50, 95, value=80, step=5, label="Automation rate (%)")
                        gr.Button("⚡ Calculate ROI", variant="primary").click(
                            fn=lambda t,h,r,a: (calc_roi(t,h,r,a), get_roi_chart(t,h,r,a)),
                            inputs=[t_size, h_day, h_rate, a_rate],
                            outputs=[gr.Textbox(label="Analysis", lines=22, interactive=False), gr.Plot(label="")]
                        )
                    with gr.Column():
                        roi_out = gr.Textbox(label="ROI Analysis", lines=22, interactive=False, value=calc_roi(10,2,500,80))
                roi_chart = gr.Plot(value=get_roi_chart(10,2,500,80), label="")

            # ── TAB 5: AUDIT LOG
            with gr.TabItem("📋  Audit Log"):
                gr.HTML('<div style="font-family:monospace;font-size:11px;color:#94a3b8;padding:8px 0;">// AUDIT LOG · Full Transparency</div>')
                audit_df = gr.Dataframe(value=get_audit_log_df(), label="Agent Action Log", interactive=False, wrap=True)
                with gr.Row():
                    exp_fmt = gr.Radio(["CSV", "JSON"], value="CSV", label="Format")
                    gr.Button("📥  Export", variant="secondary").click(
                        fn=export_audit, inputs=exp_fmt,
                        outputs=[gr.File(label="Download"), gr.Textbox(label="Status", interactive=False)]
                    )

        gr.HTML('<div style="border-top:1px solid #1e2d4d;margin-top:24px;padding:16px 0;'
                'font-family:monospace;font-size:11px;color:#64748b;text-align:center;">'
                'Nova CoPilot for Screens · Amazon Nova Hackathon 2025 · '
                '<span style="color:#06b6d4;">Nova 2 Lite · Nova Act · Nova Embeddings · Nova 2 Sonic</span></div>')

    print('\n✅ App built! Launching...\n')
    demo.launch(
        share=True,           # 📡 Public Gradio link for Colab
        server_name="0.0.0.0",
        server_port=7860,
        show_error=True,
    )

build_and_launch()